services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USER=${SPRING_DATASOURCE_USER}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - DYNAMO_DB_NOTIFICATION_TOKEN_TABLE=${DYNAMO_DB_NOTIFICATION_TOKEN_TABLE}